GET http://localhost:5050/users

#######

POST http://localhost:5050/users/new HTTP/1.1
content-type: application/json

{
  "firstName": "aaa",
  "lastName": "aaa",
  "email": "aaa@gmail.com",
  "password" : "aaa",
  "age": 30
}

#######

PATCH http://localhost:5050/users/6463b7fd345f89b8c9a5f3b9 HTTP/1.1
content-type: application/json

{
  "firstName": "bbb",
  "lastName": "bbb",
  "email": "bbb@gmail.com",
  "password" : "bbb",
  "age": 87
}

#######

DELETE  http://localhost:5050/users/delete/6463b7fd345f89b8c9a5f3b9
